<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Tracker $block */
?>
<!-- Tag_Lengow -->
<img
    src="https://trk.lgw.io/lead?account_id=<?= $block->getData('account_id') ?>&order_ref=<?= $block->getData('order_ref') ?>&amount=<?= $block->getData('amount') ?>&currency=<?= $block->getData('currency') ?>&payment_method=<?= $block->getData('payment_method') ?>&cart=<?= $block->getData('cart') ?>&cart_number=<?= $block->getData('cart_number') ?>&newbiz=<?= $block->getData('newbiz') ?>"
    alt="" style="width: 1px; height: 1px; border: none;"/>
<img
    src="https://trk.lgw.io/validation?account_id=<?= $block->getData('account_id') ?>&order_ref=<?= $block->getData('order_ref') ?>&payment_method=<?= $block->getData('payment_method') ?>&valid=<?= $block->getData('valid') ?>"
    alt="" style="width: 1px; height: 1px; border: none;"/>
<!-- /Tag_Lengow -->


