reviewers:
  defaults:
    - repository-owners
  groups:
    repository-owners:
      - team:E-commerce-Plugins
    devops:
      - team:Platform

files:
  '**':
    - repository-owners
  '.github/**':
    - devops

options:
  number_of_reviewers: 2
  ignore_draft: true
  enable_group_assignment: true
