<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Main $block */
?>
<div id="lgw-bad-payer" class="lgw-container">
    <div class="lgw-box">
        <div class="lgw-row">
            <div class="lgw-col-6 display-inline-block">
                <h3 class="text-center"><?= $block->escapeHtml(__('Your account has been temporarily shut down')) ?></h3>
                <p class="text-center"><?= $block->escapeHtml(__('We are sorry to inform you that we have had to limit access to your account temporarily because the automatic payment of your subscription failed.')) ?></p>
                <p class="text-center"><?= $block->escapeHtml(__('The posting of your catalogue has been suspended. We strongly suggest that you get in touch with us at')) ?>
                    <a href="mailto:backoffice@lengow.com">backoffice@lengow.com</a>
                    <?= $block->escapeHtml(__('or by phone at +44 203 318 2632')) ?>
                </p>
                <p class="text-center"><?= $block->escapeHtml(__('We hope to work with you again in the near future.')) ?></p>
                <div class="text-center">
                    <button type="button" class="lgw-btn">
                        <a href="http://my.lengow.net/" target="_blank">
                            <?= $block->escapeHtml(__('View my billing information')) ?>
                        </a>
                    </button>
                </div>
                <div class="text-center">
                    <button type="button"  class="lgw-btn">
                        <a href="<?= $block->getUrl('lengow/home/refresh') ?>">
                            <?= $block->escapeHtml(__('Refresh my account')) ?>
                        </a>
                    </button>
                </div>
            </div>
            <div class="lgw-col-6">
                <div class="vertical-center">
                    <img src="<?= $block->getViewFileUrl('Lengow_Connector::images/lengow-blue.png') ?>" class="center-block" alt="lengow"/>
                </div>
            </div>
        </div>
    </div>
</div>