<?php
/**
 * Copyright 2021 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Main $block */
$escaper = $block->getEscaper();
?>

<div id="lgw-connection-cms" style="text-align: center">
    <div class="lgw-content-section">
        <h2><?= $escaper->escapeHtml(__('Please enter your API Lengow credentials')) ?></h2>
    </div>
    <div class="lgw-content-input">
        <div>
        <input type="text"
               name="lgwAccessToken"
               class="js-credentials-input"
               placeholder="<?= $escaper->escapeHtml(__('Enter your access token')) ?>">
        </div>
        <div>
        <input type="text"
               name="lgwSecret"
               class="js-credentials-input"
               placeholder="<?= $escaper->escapeHtml(__('Enter your secret')) ?>">
        </div>
    </div>
    <div class="lgw-content-section">
        <p><?= $escaper->escapeHtml(__('Find these credentials in your account settings, section A.P.I')) ?></p>
        <p>
            <?= $escaper->escapeHtml(__('Need help?')) ?>
            <a href="<?= $escaper->escapeHtml($block->getHelpCenterLink()) ?>" target="_blank">
                <?= $escaper->escapeHtml(__('Check out our Help Center')) ?>
            </a>
        </p>
    </div>
    <div>
        <button class="lgw-btn-disabled lgw-btn lgw-btn-progression js-connect-cms"
                data-href="<?= /** @noEscape */ $block->getUrl('lengow/home/cmsResult')?>">
            <div class="btn-inner">
                <div class="btn-step default js-connect">
                    <?= $escaper->escapeHtml(__('Connect to Lengow')) ?>
                </div>
                <div class="btn-step loading">
                    <?= $escaper->escapeHtml(__('Connecting...')) ?>
                </div>
            </div>
        </button>
    </div>
</div>
