<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Home\Dashboard $block */
?>
<div class="lgw-container">
    <div class="lgw-box lgw-home-header text-center">
        <img src="<?= $block->getViewFileUrl('Lengow_Connector::images/lengow-white-big.png') ?>" alt="lengow">
        <h1><?= $block->escapeHtml(__('Hi! Welcome back!')) ?></h1>
        <a href="<?= $block->getLengowSolutionUrl() ?>" class="lgw-btn" target="_blank" title="<?= $block->escapeHtml(__('Go to Lengow')) ?>">
            <?= $block->escapeHtml(__('Go to Lengow')) ?>
        </a>
    </div>
    <div class="lgw-row lgw-home-menu text-center">
        <div class="lgw-col-4">
            <a href="<?= $block->getUrl('lengow/product/index') ?>" class="lgw-box-link" title="<?= $block->escapeHtml(__('Products')) ?>">
                <div class="lgw-box">
                    <img src="<?= $block->getViewFileUrl('Lengow_Connector::images/home-products.png') ?>" class="img-responsive">
                    <h2><?= $block->escapeHtml(__('Products')) ?></h2>
                    <p><?= $block->escapeHtml(__('Take a look at all available products so that you can prepare your catalogue')) ?></p>
                </div>
            </a>
        </div>
        <div class="lgw-col-4">
            <a href="<?= $block->getUrl('lengow/order/index') ?>" class="lgw-box-link" title="<?= $block->escapeHtml(__('Orders')) ?>">
                <div class="lgw-box">
                    <img src="<?= $block->getViewFileUrl('Lengow_Connector::images/home-orders.png') ?>" class="img-responsive">
                    <h2>
                        <?= $block->escapeHtml(__('Orders')) ?>
                        <?php if($block->getNumberOrderToBeSent()): ?>
                            <span class="lgw-label lgw-label red"><?= $block->getNumberOrderToBeSent() ?></span>
                        <?php endif; ?>
                    </h2>
                    <p><?= $block->escapeHtml(__('Manage your orders directly on your Magento dashboard')) ?></p>
                </div>
            </a>
        </div>
        <div class="lgw-col-4">
            <a href="<?= $block->getUrl('adminhtml/system_config/edit/section/lengow_global_options') ?>" class="lgw-box-link" title="<?= $block->escapeHtml(__('Settings')) ?>">
                <div class="lgw-box">
                    <img src="<?= $block->getViewFileUrl('Lengow_Connector::images/home-settings.png') ?>" class="img-responsive">
                    <h2><?= $block->escapeHtml(__('Settings')) ?></h2>
                    <p><?= $block->escapeHtml(__('Configure your Magento plugin main settings')) ?></p>
                </div>
            </a>
        </div>
    </div>
    <div class="lgw-box">
        <h2><?= $block->escapeHtml(__('Need some help?')) ?></h2>
        <p>
            <a href="<?= $block->getUrl('lengow/help/index') ?>" title="<?= $block->escapeHtml(__('Get in touch with Lengow.')) ?>">
                <?= $block->escapeHtml(__('Get in touch with Lengow.')) ?>
            </a>
        </p>
        <p>
            <a href="<?= $block->escapeHtml(__('https://supportlengow.zendesk.com/hc/en-us/articles/360012204551')) ?>" target="_blank"
               title="<?= $block->escapeHtml(__('Visit our Help Center')) ?>"><?= $block->escapeHtml(__('Visit our Help Center')) ?></a>
            <?= $block->escapeHtml(__('for detailed information on how to configure your Magento plugin properly')) ?>
        </p>
    </div>
</div>