<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Main $block */
?>
<?php if ($block->isNewMerchant() || $block->isSync()): ?>
    <?= $block->getChildHtml('lengow_home_new') ?>
    <input type="hidden" id="lengow_sync_link" value="<?= $block->isSync() ?>">
    <input type="hidden" id="lengow_lang_iso" value="<?= $block->getIsoCode() ?>">
    <input type="hidden" id="lengow_url" value="<?= $block->getLengowUrl() ?>">
<?php elseif ($block->freeTrialIsExpired()): ?>
    <?= $block->getChildHtml('lengow_home_free_trial') ?>
<?php else: ?>
    <div class="lgw-container"><?= $block->getChildHtml('lengow_header') ?></div>
    <?= $block->getChildHtml('lengow_home_dashboard') ?>
<?php endif; ?>
<?= $block->getChildHtml('lengow_footer') ?>
