<?php
/**
 * Copyright 2021 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Main $block */
$escaper = $block->getEscaper();
?>

<div id="lengow_home_wrapper" class="cms-global">
    <div id="lgw-connection-container" class="lgw-container lgw-connection text-center">
        <div class="lgw-content-section">
            <div class="lgw-logo">
                <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Lengow_Connector::images/lengow-blue.png')) ?>" class="img-responsive">
            </div>
        </div>
        <div id="lgw-connection-content">
            <div id="lgw-connection-home">
                <div class="lgw-content-section">
                    <p><?= $escaper->escapeHtml(__('Lengow helps you optimize your business worldwide!')) ?></p>
                    <p><?= $escaper->escapeHtml(__('Through the platform, you can automatically publish your product catalogue on marketplaces, comparison websites, affiliate network, and retargeting campaigns.')) ?></p>
                    <p><?= $escaper->escapeHtml(__('Explore your opportunities for international growth with 1,600 sales channels in 42 different countries.')) ?></p>
                </div>
                <div class="lgw-module-illu">
                    <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Lengow_Connector::images/connected-lengow.png')) ?>"
                         class="lgw-module-illu-lengow"
                         alt="lengow">
                    <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Lengow_Connector::images/plug-grey.png')) ?>"
                         class="lgw-module-illu-plug"
                         alt="plug">
                    <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Lengow_Connector::images/connected-magento.png')) ?>"
                         class="lgw-module-illu-module"
                         alt="magento">
                </div>
                <p><?= $escaper->escapeHtml(__('Just one more step to go to install your Lengow plugin for Magento')) ?></p>
                <div>
                    <button class="lgw-btn lgw-btn-green js-go-to-credentials" data-href="<?= $escaper->escapeUrl($block->getUrl('lengow/home/cms')) ?>">
                        <?= $escaper->escapeHtml(__('Connect my Magento with Lengow')) ?>
                    </button>
                    <br/>
                    <p>
                        <?= $escaper->escapeHtml(__("You don't have a Lengow account?")) ?>
                        <a href="<?= $escaper->escapeUrl($block->getLengowSolutionUrl()) ?>" target="_blank">
                            <?= $escaper->escapeHtml(__('Sign up for free')) ?>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
