<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Help\Content $block */
?>

<div class="lgw-box">
    <div class="text-center">
        <h2><?= $block->escapeHtml(__('Get a little help from your support team!')) ?></h2>
        <p>
            <?= $block->escapeHtml(__('Ask us anything about Lengow or share your feedback with')) ?>
            <a href="<?= $block->escapeHtml(__('https://supportlengow.zendesk.com/hc/en-us/requests/new')) ?>" target="_blank" title="Lengow Support">
                <?= $block->escapeHtml(__('Lengow Support.')) ?>
            </a>
        </p>
        <p><?= $block->escapeHtml(__('We’ll do our best to get back to you during regular business hours (Monday to Friday – 9am to 6pm GMT+1).')) ?></p>
        <p><?= $block->escapeHtml(__('You can also find answers in our')) ?>
            <a href="<?= $block->escapeHtml(__('https://en.lengow.help/help/magento2')) ?>" class="sub-link" target="_blank" title="Help Center">
                <?= $block->escapeHtml(__('Magento 2 dedicated guide')) ?>
            </a>
        </p>
    </div>
</div>


