<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Main $block */
$escaper = $block->getEscaper();
?>

<div class="lgw-container">
    <div class="lgw-box">
        <div class="text-center">
            <h2><?= $escaper->escapeHtml(__('Get a little help from your support team!')) ?></h2>
            <p>
                <?= $escaper->escapeHtml(__('Ask us anything about Lengow or share your feedback with')) ?>
                <a href="<?= $escaper->escapeHtml($block->getSupportLink()) ?>"
                   target="_blank"
                   title="Lengow Support">
                    <?= $escaper->escapeHtml(__('Lengow Support.')) ?>
                </a>
            </p>
            <p><?= $escaper->escapeHtml(__('We’ll do our best to get back to you during regular business hours (Monday to Friday – 9am to 6pm GMT+1).')) ?></p>
            <p><?= $escaper->escapeHtml(__('You can also find answers in our')) ?>
                <a href="<?= $escaper->escapeHtml($block->getHelpCenterLink()) ?>"
                   target="_blank"
                   title="Help Center">
                    <?= $escaper->escapeHtml(__('Magento 2 dedicated guide')) ?>
                </a>
            </p>
        </div>
    </div>
</div>


