<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Main $block */
?>
<?= '<div class="lgw-container">' ?>
<?= $block->getChildHtml('lengow_header') ?>
<?= '</div>' ?>
<?php if ($block->freeTrialIsExpired()): ?>
    <?= $block->getChildHtml('lengow_home_free_trial') ?>
<?php else:?>
    <?= $block->getChildHtml('lengow_dashboard_content') ?>
<?php endif ?>
<?= $block->getChildHtml('lengow_footer') ?>
