<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Order\Header $block */
?>

<div class="lgw-box">
    <?php if ($block->preprodModeIsEnabled()): ?>
        <p class="blue_frame" style="line-height: 20px;">
            <?= $block->escapeHtml(__('You are in pre-production mode. You can import orders, but no interaction with Lengow is possible.')) ?>
            <a href="<?= $block->getUrl('system_config/edit/section/lengow_import_options') ?>"
               title="<?= $block->escapeHtml(__('Change this')) ?>">
                <?= $block->escapeHtml(__('Change this')) ?>
            </a>
        </p>
    <?php endif; ?>
    <div id="lengow_order_with_error">
        <?= $block->getImportHelper()->getOrderWithErrorPrint() ?>
    </div>
    <div id="lengow_order_to_be_sent">
        <?= $block->getImportHelper()->getOrderToBeSentPrint() ?>
    </div>
    <div id="lengow_last_importation">
        <?= $block->getImportHelper()->getLastImportDatePrint() ?>
    </div>
    <div><?= $block->getImportHelper()->getReportMailPrint() ?></div>
    <div>
        <button
            type="button"
            id="lengow_import_orders"
            class="lgw-btn lengow_import_orders-js"
            data-href="<?= $block->getUrl('lengow/order/index/action/import_all/'); ?>?isAjax=true">
            <?= $block->escapeHtml(__('Synchronize Orders')); ?>
        </button>
    </div>
</div>