<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Toolbox\Content $block */
$escaper = $block->getEscaper();
?>

<div class="lgw-box">
    <h2><i class="fa fa-rocket"></i> <?= $escaper->escapeHtml(__('Lengow Toolbox')) ?></h2>
    <br />
    <div id="lengow_see_global" class="lgw-switch checked">
        <label>
            <div>
                <span></span>
                <input type="checkbox" data-action="see_global_information" class="lengow_switch_option" checked="checked">
            </div>
            <?= $escaper->escapeHtml(__('Global information')) ?>
        </label>
    </div>
    <div id="global-information">
        <div class="lengow-block-full">
            <h3><i class="fa fa-check"></i> <?= $escaper->escapeHtml(__('Checklist')) ?></h3>
            <?= /* @noEscape */ $block->getCheckList() ?>
        </div>
        <div class="lengow-block-full">
            <h3><i class="fa fa-cog"></i> <?= $escaper->escapeHtml(__('Plugin information')) ?></h3>
            <?= /* @noEscape */ $block->getPluginInformation() ?>
        </div>
        <div class="lengow-block-full">
            <h3><i class="fa fa-download"></i> <?= $escaper->escapeHtml(__('Import information')) ?></h3>
            <?= /* @noEscape */ $block->getImportInformation() ?>
        </div>
        <div class="clear"></div>
    </div>
    <div class="lengow-content-header"></div>
    <div class="lgw-switch" id="lengow_see_store">
        <label>
            <div>
                <span></span>
                <input type="checkbox" data-action="see_store_information" class="lengow_switch_option">
            </div>
            <?= $escaper->escapeHtml(__('Store information')) ?>
        </label>
    </div>
    <div id="store-information">
        <div class="lengow-block-full">
            <h3><i class="fa fa-upload"></i> <?= $escaper->escapeHtml(__('Export information')) ?></h3>
            <?= /* @noEscape */ $block->getExportInformation() ?>
        </div>
        <div class="lengow-block-full">
            <h3><i class="fa fa-list"></i> <?= $escaper->escapeHtml(__('Content folder media')) ?></h3>
            <?= /* @noEscape */ $block->getFileInformation() ?>
        </div>
        <div class="clear"></div>
    </div>
    <div class="lengow-content-header"></div>
    <div class="lgw-switch" id="lengow_see_cron">
        <label>
            <div>
                <span></span>
                <input type="checkbox" data-action="see_cron_information" class="lengow_switch_option">
            </div>
            <?= $escaper->escapeHtml(__('Magento cron schedule')) ?>
        </label>
    </div>
    <div id="cron-information">
        <div class="lengow-block-full">
            <h3><i class="fa fa-clock-o"></i> <?= $escaper->escapeHtml(__('Lengow export cron jobs')) ?></h3>
            <?= /* @noEscape */ $block->getCronInformation('export') ?>
        </div>
        <div class="lengow-block-full">
            <h3><i class="fa fa-clock-o"></i> <?= $escaper->escapeHtml(__('Lengow import cron jobs')) ?></h3>
            <?= /* @noEscape */ $block->getCronInformation('import') ?>
        </div>
        <div class="clear"></div>
    </div>
    <div class="lengow-content-header"></div>
    <div class="lgw-switch" id="lengow_see_checksum">
        <label>
            <div>
                <span></span>
                <input type="checkbox" data-action="see_checksum_information" class="lengow_switch_option">
            </div>
            <?= $escaper->escapeHtml(__('File Checksum integrity')) ?>
        </label>
    </div>
    <div id="checksum-information">
        <div class="lengow-block-full">
            <?= /* @noEscape */ $block->checkFileMd5() ?>
        </div>
        <div class="clear"></div>
    </div>
    <div class="lengow-content-header"></div>
    <div class="lgw-switch" id="lengow_see_action">
        <label>
            <div>
                <span></span>
                <input type="checkbox" data-action="see_action_information" class="lengow_switch_option">
            </div>
            <?= $escaper->escapeHtml(__('Lengow actions')) ?>
        </label>
    </div>
</div>



