<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Main $block */
?>

<?= $block->getChildHtml('lengow_header') ?>
<?= $block->getChildHtml('lengow_toolbox_content') ?>
<div id="lengow_action_grid">
    <?= $block->getChildHtml('lengow_action_listing') ?>
</div>
<?= $block->getChildHtml('lengow_footer') ?>
