<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Sales\Order\Tab\Info $block */

$fields = $block->getFields();
$escaper = $block->getEscaper();
?>

<div class="lgw-box">
    <div id="lgw-info-title">
        <h2>
            <i class="fa fa-rocket"></i>
            <?= $escaper->escapeHtml(__('Lengow informations')) ?>
        </h2>
    </div>
    <?php if ($block->isOrderImportedByLengow()): ?>
        <?php if ($block->isOrderFollowedByLengow()): ?>
            <?php if (!$block->debugModeIsEnabled()): ?>
                <div id="lgw-info-btn">
                    <button type="button" class="primary">
                        <a href="<?= $escaper->escapeUrl($block->getUrl('lengow/order/synchronize', ['order_id' => $block->getOrderId(), 'lengow_order_id' => $block->getLengowOrderId()])) ?>"
                           onclick="return confirm('<?= $escaper->escapeHtml(__('Do you really want to synchronize the order?')) ?>')">
                            <?= $escaper->escapeHtml(__('Synchronize ID')) ?>
                        </a>
                    </button>
                    <button type="button" class="primary">
                        <a href="<?= $escaper->escapeUrl($block->getUrl('lengow/order/reimport', ['order_id' => $block->getOrderId(), 'lengow_order_id' => $block->getLengowOrderId()])) ?>"
                           onclick="return confirm('<?= $escaper->escapeHtml(__('Do you really want to re-import the order?')) ?>')">
                            <?= $escaper->escapeHtml(__('Re-import order')) ?>
                        </a>
                    </button>
                    <?php if ($block->canReSendAction()): ?>
                        <button type="button" class="primary">
                            <a href="<?= $escaper->escapeUrl($block->getUrl('lengow/order/resend', ['order_id' => $block->getOrderId(), 'status' => $block->getOrderStatus()])) ?>"
                               onclick="return confirm('<?= $escaper->escapeHtml(__('Do you really want to %1 the order?', [$block->getOrderStatus()])) ?>')">
                                <?= $escaper->escapeHtml(__('Resend Action')) ?>
                            </a>
                        </button>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <div class="clear"></div>
            <div class="lengow-block-full">
                <table cellpadding="0" cellspacing="0">
                    <?php foreach ($fields as $field): ?>
                        <tr>
                            <td>
                                <b><?= $escaper->escapeHtml($field['label']) ?></b>
                            </td>
                            <td align="right">
                                <?php if ('JSON format' === (string)$field['label']): ?>
                                    <textarea disabled="disabled">
                                        <?= $escaper->escapeHtml($field['value']) ?>
                                    </textarea>
                                <?php else: ?>
                                    <?= $escaper->escapeHtml($field['value']) ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        <?php else: ?>
            <div class="clear"></div>
            <p><?= $escaper->escapeHtml(__('Due to a reimportation, this order is not tracked by Lengow')) ?></p>
        <?php endif; ?>
    <?php else: ?>
        <div class="clear"></div>
        <p><?= $escaper->escapeHtml(__('This order is not from Lengow')) ?></p>
    <?php endif; ?>
</div>
