<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Footer $block */
?>

<div id="footer" class="lgw-footer">
    <div class="text-center">
        <a href="<?= $block->getUrl('lengow/toolbox/index') ?>" class="sub-link" title="<?= $block->escapeHtml(__('Toolbox')) ?>">
            <?= $block->escapeHtml(__('Toolbox')) ?>
        </a> |
        <a href="<?= $block->getUrl('lengow/legal/index') ?>" class="sub-link" title="<?= $block->escapeHtml(__('Legal notices')) ?>">
            <?= $block->escapeHtml(__('Legal notices')) ?>
        </a> |
        <?= $block->escapeHtml(__('Lengow Magento Plugin')) ?> - v.<?= $block->getPluginVersion() ?>
        <?php if($block->isPreprodPlugin()): ?>
            <span class="lgw-label-preprod">preprod</span>
        <?php endif; ?>
        |
        <?= $block->getPluginCopyright() ?>
        <a href="<?= $block->escapeHtml(__('http://www.lengow.com/')) ?>" class="sub-link" title="Lengow.com" target="_blank">
            Lengow
        </a>
    </div>
</div>
