<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Footer $block */
?>

<div id="footer" class="lgw-footer">
    <div class="pull-right">
        <a href="" class="sub-link" title="<?= $block->escapeHtml(__('Toolbox')) ?>">
            <?= $block->escapeHtml(__('Toolbox')) ?>
        </a> |
        <a href="" class="sub-link" title="<?= $block->escapeHtml(__('Legal notices')) ?>">
            <?= $block->escapeHtml(__('Legal notices')) ?>
        </a> |
        <?= $block->escapeHtml(__('Lengow Magento Plugin')) ?> - v.<?= $block->getPluginVersion() ?> |
        <?= $block->getPluginCopyright() ?>
        <a href="<?= $block->escapeHtml(__('http://www.lengow.com/')) ?>" class="sub-link" title="Lengow.com" target="_blank">
            Lengow
        </a>
    </div>
</div>
