<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Header $block */
?>
<?php if($block->preprodModeIsEnabled()): ?>
    <span id="lgw-preprod">
        <?= $block->escapeHtml(__('Pre-production mode')) ?>
    </span>
<?php endif; ?>
<div class="lgw-row">
    <p class="text-left lgw-col-6">
        <?php if($block->newPluginVersionIsAvailable()): ?>
            <span id="lgw-plugin-available">
                <?= $block->escapeHtml(__('A new version %1 is available!', [$block->getNewPluginVersion()])) ?>
                <a href="<?= $block->getNewPluginDownloadLink() ?>" target="_blank" title="<?= $block->escapeHtml(__('Download')) ?>">
                    <?= $block->escapeHtml(__('Download')) ?>
                </a>
            </span>
        <?php endif; ?>
    </p>
    <p class="text-right lgw-col-6">
        <?php if($block->freeTrialIsEnabled()): ?>
            <span id="lgw-counter">
                <?= $block->escapeHtml(__('Trial period: %1 day(s) left.', [$block->getFreeTrialDays()])) ?>
                <a href="<?= $block->getLengowSolutionUrl() ?>" target="_blank" title="<?= $block->escapeHtml(__('Subscribe')) ?>">
                    <?= $block->escapeHtml(__('Subscribe')) ?>
                </a>
            </span>
        <?php endif; ?>
    </p>
</div>
