<?php
/**
 * Copyright 2017 Lengow SAS
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Lengow\Connector\Block\Adminhtml\Main $block */
$escaper = $block->getEscaper();
?>
<?php if($block->debugModeIsActive()): ?>
    <span id="lgw-debug">
        <?= $escaper->escapeHtml(__('Debug Mode')) ?>
    </span>
<?php endif; ?>
<div class="lgw-row lgw-header">
    <p class="text-left lgw-col-6">
        <?php if($block->newPluginVersionIsAvailable()): ?>
            <span id="lgw-plugin-available">
                <?= $escaper->escapeHtml(__('A new version %1 is available!', [$block->getNewPluginVersion()])) ?>
                <button class="lgw-btn-link mod-inline js-upgrade-plugin-modal-open">
                    <?= $escaper->escapeHtml(__('Download')) ?>
                </button>
            </span>
        <?php endif; ?>
    </p>
    <p class="text-right lgw-col-6">
        <?php if($block->freeTrialIsEnabled()): ?>
            <span id="lgw-counter">
                <?= $escaper->escapeHtml(__('Trial period: %1 day(s) left.', [$block->getFreeTrialDays()])) ?>
                <a href="<?= $block->getLengowSolutionUrl() ?>" target="_blank" title="<?= $escaper->escapeHtml(__('Subscribe')) ?>">
                    <?= $escaper->escapeHtml(__('Subscribe')) ?>
                </a>
            </span>
        <?php endif; ?>
    </p>
</div>
