<div class="lgw-box">
    <div id="lengow_check_store">
        <a class="lengow_check_store lengow_tooltip"
           data-id_store="<?php echo $this->getStore()->getId(); ?>"
           data-href="<?php echo $this->getBackendHelper()->getUrl('lengow/product/'); ?>?isAjax=true">
        </a>
    </div>
<div class="lengow_export_feed">
    <a href="<?php echo $this->getDataHelper()->getExportUrl($this->getStore()->getId(), array('stream' => 1, 'update_export_date' => 0)); ?>"
       target="_blank">
        <i class="fa fa-download lengow_tooltip">
            <span ><?php echo __('Download'); ?></span>
        </i>
    </a>
</div>
<div class="text-center">
    <h3 id="lengow_product_store_name" class="lengow_product_store_name lengow_tooltip">
        <?php echo $this->getStore()->getName(); ?>
        <span>
            <?php echo $this->getStore()->getName(); ?> (<?php echo $this->getStore()->getId(); ?>)
            <?php echo $this->getStore()->getBaseUrl(); ?>
        </span>
    </h3>
    <br>
    <br>
    <div class="products-exported">
        <div id="parent_exported_products">
                <span id="exported_products" class="lengow_exported stats-big-value">
                    <?php echo $this->getExport()->getTotalExportedProduct(); ?>
                </span>
            <span> <?php echo __('products exported'); ?></span>
        </div>

    </div>
    <br>
    <div id="parent_total_products">
            <span id="total_products"  class="lengow_total stats-big-value">
                <?php echo $this->getExport()->getTotalProduct(); ?>
            </span>
        <span> <?php echo __('products available'); ?></span>
    </div>
    <br>
    <br>
    <hr>
    <div class="lgw-switch <?php if ($this->getConfigHelper()->get('selection_enable', $this->getStore()->getId()) == '1'): ?> checked <?php endif; ?>">
        <label>
            <div><span></span>
                <input
                    type="checkbox"
                    name="lengow_export_selection" class="lengow_switch_option"
                    id="change_option_selected"
                    data-href="<?php echo $this->getBackendHelper()->getUrl('lengow/product/'); ?>?isAjax=true"
                    data-action="change_option_selected"
                    data-id_store="<?php echo $this->getStore()->getId(); ?>"
                    value="1" <?php if ($this->getConfigHelper()->get('selection_enable', $this->getStore()->getId()) == '1'): ?>
                    checked="checked" <?php endif; ?>>
            </div> <?php echo __('Include specific products'); ?>
        </label>
    </div>
    <i class="fa fa-info-circle lengow_tooltip">
            <span class ="lengow_specific_product_support">
                <?php echo __('Use this option to select products one by one'); ?>
            </span>
    </i>
</div>
</div>